# Generated by Django 4.2.7 on 2024-02-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCarte',
            fields=[
                ('tag', models.CharField(choices=[('Date', 'Date'), ('Personnage/Figure', 'Personnage/Figure'), ('Formule', 'Formule'), ('Définition', 'Définition'), ('Mot', 'Mot'), ('Verbe', 'Verbe'), ('Citation', 'Citation'), ('Généralité', 'Généralité')], max_length=20)),
                ('date_ajout', models.DateField(auto_now_add=True, null=True)),
                ('devant', models.CharField(blank=True, max_length=100, null=True)),
                ('image_devant', models.ImageField(blank=True, null=True, upload_to='media/image_devant/')),
                ('dos', models.CharField(blank=True, max_length=100, null=True)),
                ('image_dos', models.ImageField(blank=True, null=True, upload_to='media/image_dos/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'A Refaire immédiatement')], default=2)),
                ('date_de_revue', models.DateTimeField()),
                ('apprise', models.BooleanField(default=False)),
                ('demiapprise', models.BooleanField(default=False)),
                ('ease', models.FloatField(default=2.5)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.flashcarte')),
            ],
        ),
    ]
