# Generated by Django 4.2.7 on 2024-02-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connaissance.cours'),
        ),
    ]
